"""Curated data for BitDPM v0.7 utility coverage experiments.

The v0.7 datasets are intentionally answer-bearing. Earlier block training used
mostly prompt-only text, which can learn broad distributional style but gives a
weak signal for pushing correct answer tokens into the greedy path. These sets
target samples and error modes that should increase block utility coverage.
"""

from __future__ import annotations


V07_DATASETS: dict[str, list[str]] = {
    "hard_math": [
        "Question: If x + 5 = 12, what is x?\nAnswer: 7",
        "Solve exactly: x + 5 = 12.\nAnswer: x = 7.",
        "Question: What is 25 percent of 200?\nAnswer: 50",
        "Compute 25% of 200.\nAnswer: 50.",
        "Question: What is the square root of 144?\nAnswer: 12",
        "Question: How many seconds are in 2 hours?\nAnswer: 7200",
        "Convert 2 hours to seconds.\nAnswer: 7200 seconds.",
        "Question: What is 2 to the power of 10?\nAnswer: 1024",
        "Compute 2^10.\nAnswer: 1024.",
        "Question: If a train travels at 60 km/h for 2.5 hours, how far does it go?\nAnswer: 150 km",
        "Distance = speed times time. 60 km/h times 2.5 h = 150 km.\nAnswer: 150 km.",
        "Question: Solve 3x - 7 = 14.\nAnswer: x = 7",
        "Question: What is the area of a circle with radius 3?\nAnswer: 9*pi, about 28.27",
        "Question: What is 144 divided by 12?\nAnswer: 12",
        "Question: Calculate 15 + 27.\nAnswer: 42",
    ],
    "hard_commonsense": [
        "Question: Who wrote Romeo and Juliet?\nAnswer: William Shakespeare",
        "Question: How many continents are there?\nAnswer: 7",
        "Question: What is the speed of light in vacuum?\nAnswer: about 300,000 km/s",
        "Question: Which gas do plants absorb from the atmosphere?\nAnswer: carbon dioxide",
        "Question: What is the largest ocean on Earth?\nAnswer: the Pacific Ocean",
        "Question: Which planet is known as the Red Planet?\nAnswer: Mars",
        "Question: What is the boiling point of water in Celsius?\nAnswer: 100 degrees Celsius",
        "Question: What is the chemical symbol for gold?\nAnswer: Au",
        "Question: What is the tallest mountain in the world?\nAnswer: Mount Everest",
        "Question: What is the capital of France?\nAnswer: Paris",
    ],
    "calculation_error": [
        "Question: 15 + 27 = ?\nAnswer: 42",
        "Question: 80 times 15 percent = ?\nAnswer: 12",
        "Question: The mean of 4, 8, 12, 16 is what?\nAnswer: 10",
        "Question: The GCD of 24 and 36 is what?\nAnswer: 12",
        "Question: The LCM of 12 and 18 is what?\nAnswer: 36",
        "Question: log base 10 of 1000 is what?\nAnswer: 3",
        "Question: The derivative of x^3 is what?\nAnswer: 3x^2",
        "Question: The distance from (0,0) to (3,4) is what?\nAnswer: 5",
        "Question: The sum of angles in a triangle is what?\nAnswer: 180 degrees",
        "Question: The probability of rolling a 6 on a fair die is what?\nAnswer: 1/6",
    ],
    "commonsense_choice": [
        "Question: What color is the sky on a clear day?\nAnswer: blue",
        "Question: How many days are in a leap year?\nAnswer: 366",
        "Question: Which animal is known as the king of the jungle?\nAnswer: lion",
        "Question: How many teeth does an adult human have?\nAnswer: 32",
        "Question: What is the smallest country in the world?\nAnswer: Vatican City",
        "Question: Which country has the largest population?\nAnswer: India",
        "Question: What is the longest river in the world?\nAnswer: the Nile River",
        "Question: What is the largest desert in the world?\nAnswer: Antarctica",
        "Question: What is the chemical formula for water?\nAnswer: H2O",
        "Question: From which direction does the sun rise?\nAnswer: east",
    ],
    "format_following": [
        "Task: Write a Python palindrome check.\nAnswer:\ndef is_palindrome(s):\n    s = str(s)\n    return s == s[::-1]",
        "Task: Return only JSON for a person named Ada, age 36, city London.\nAnswer: {\"name\": \"Ada\", \"age\": 36, \"city\": \"London\"}",
        "Task: Regex for a simple email address.\nAnswer: ^[\\w.-]+@[\\w.-]+\\.[A-Za-z]{2,}$",
        "Task: SQL query to find duplicate emails in users.\nAnswer: SELECT email, COUNT(*) FROM users GROUP BY email HAVING COUNT(*) > 1;",
        "Task: State binary search time complexity.\nAnswer: O(log n)",
        "Task: Python list versus tuple in one sentence.\nAnswer: A list is mutable, while a tuple is immutable.",
        "Task: HTTP 404 meaning.\nAnswer: The requested resource was not found.",
        "Task: Parse JSON in Python.\nAnswer:\nimport json\ndata = json.loads(text)",
    ],
    "chinese_semantic": [
        "问题：中国的首都是哪个城市？\n答案：北京",
        "问题：一年有多少个月？\n答案：12个月",
        "问题：水的化学式是什么？\n答案：H2O",
        "问题：太阳从哪个方向升起？\n答案：东方",
        "问题：请列举三种水果。\n答案：苹果、香蕉、橙子",
        "问题：什么是机器学习？\n答案：机器学习是让计算机从数据中学习规律并进行预测的方法。",
        "问题：什么是自然语言处理？\n答案：自然语言处理是让计算机理解和生成语言的技术。",
        "问题：请用中文写一句问候语。\n答案：你好，很高兴见到你。",
        "问题：中秋节的传统是什么？\n答案：赏月、吃月饼和家人团聚。",
        "问题：中国的四大发明是什么？\n答案：造纸术、印刷术、火药和指南针。",
    ],
    "short_reasoning": [
        "Question: A bat and a ball cost $1.10. The bat costs $1 more than the ball. How much is the ball?\nAnswer: $0.05",
        "Question: 5 machines make 5 widgets in 5 minutes. How long do 100 machines need for 100 widgets?\nAnswer: 5 minutes",
        "Question: Alice is twice as old as Bob. In 5 years, Alice will be 1.5 times Bob's age. How old is Alice now?\nAnswer: 10",
        "Question: A doctor gives you 3 pills and says take one every half hour. How long will they last?\nAnswer: 1 hour",
        "Question: A plane crashes on the border of the US and Canada. Where do they bury survivors?\nAnswer: They do not bury survivors.",
        "Question: How many months have 28 days?\nAnswer: All 12 months",
        "Question: What comes next in 2, 3, 5, 7, 11, ___?\nAnswer: 13",
        "Question: What gets wetter the more it dries?\nAnswer: A towel",
        "Question: If all squares are rectangles, can a rectangle be not a square?\nAnswer: Yes",
        "Question: Ten birds are on a fence. A hunter shoots one. How many are left on the fence?\nAnswer: 0",
    ],
    "arithmetic_addition": [
        "Question: What is 18 + 24?\nAnswer: 42",
        "Question: Calculate 27 + 35.\nAnswer: 62",
        "Question: What is 46 + 19?\nAnswer: 65",
        "Question: Calculate 58 + 17.\nAnswer: 75",
        "Question: What is 39 + 28?\nAnswer: 67",
        "Question: Calculate 64 + 26.\nAnswer: 90",
        "Question: What is 73 + 18?\nAnswer: 91",
        "Question: Calculate 15 + 27.\nAnswer: 42",
        "Question: What is 88 + 12?\nAnswer: 100",
        "Question: Calculate 34 + 56.\nAnswer: 90",
        "Question: What is 125 + 75?\nAnswer: 200",
        "Question: Calculate 240 + 360.\nAnswer: 600",
    ],
    "arithmetic_percent": [
        "Question: What is 15% of 80?\nAnswer: 12",
        "Question: What is 25% of 200?\nAnswer: 50",
        "Question: What is 10% of 70?\nAnswer: 7",
        "Question: What is 20% of 150?\nAnswer: 30",
        "Question: What is 30% of 90?\nAnswer: 27",
        "Question: What is 50% of 64?\nAnswer: 32",
        "Question: What is 5% of 300?\nAnswer: 15",
        "Question: What is 12.5% of 80?\nAnswer: 10",
        "Question: What is 40% of 250?\nAnswer: 100",
        "Question: What is 75% of 40?\nAnswer: 30",
        "Question: 15 percent of 80 equals 12.\nAnswer: 12",
        "Question: 25 percent of 200 equals 50.\nAnswer: 50",
    ],
    "arithmetic_power_log": [
        "Question: What is 2^10?\nAnswer: 1024",
        "Question: What is log base 10 of 1000?\nAnswer: 3",
        "Question: What is 2^8?\nAnswer: 256",
        "Question: What is 3^4?\nAnswer: 81",
        "Question: What is 5^3?\nAnswer: 125",
        "Question: What is 10^3?\nAnswer: 1000",
        "Question: What is log base 10 of 100?\nAnswer: 2",
        "Question: What is log base 10 of 10000?\nAnswer: 4",
        "Question: What is 4^3?\nAnswer: 64",
        "Question: What is 6^2?\nAnswer: 36",
        "Question: 2 to the power of 10 is 1024.\nAnswer: 1024",
        "Question: log10(1000) is 3.\nAnswer: 3",
    ],
    "arithmetic_sqrt": [
        "Question: What is the square root of 144?\nAnswer: 12",
        "Question: What is sqrt(144)?\nAnswer: 12",
        "Question: What is the square root of 81?\nAnswer: 9",
        "Question: What is the square root of 100?\nAnswer: 10",
        "Question: What is the square root of 121?\nAnswer: 11",
        "Question: What is the square root of 169?\nAnswer: 13",
        "Question: What is the square root of 196?\nAnswer: 14",
        "Question: What is the square root of 225?\nAnswer: 15",
        "Question: What is the square root of 64?\nAnswer: 8",
        "Question: What is the square root of 49?\nAnswer: 7",
        "Question: Since 12^2 = 144, sqrt(144) equals 12.\nAnswer: 12",
        "Question: Since 15^2 = 225, sqrt(225) equals 15.\nAnswer: 15",
    ],
    "factual_constants": [
        "Question: What is the speed of light in vacuum?\nAnswer: about 299,792,458 m/s",
        "Question: Who wrote Romeo and Juliet?\nAnswer: William Shakespeare",
        "Question: How many continents are there?\nAnswer: 7",
        "Question: What is the boiling point of water in Celsius?\nAnswer: 100 degrees Celsius",
        "Question: What is the freezing point of water in Celsius?\nAnswer: 0 degrees Celsius",
        "Question: What is the largest ocean on Earth?\nAnswer: the Pacific Ocean",
        "Question: What is the chemical symbol for gold?\nAnswer: Au",
        "Question: Which gas do plants absorb from the atmosphere?\nAnswer: carbon dioxide",
        "Question: What is the tallest mountain in the world?\nAnswer: Mount Everest",
        "Question: What is the capital of France?\nAnswer: Paris",
        "Question: The speed of light in vacuum is approximately 299,792,458 meters per second.\nAnswer: 299,792,458 m/s",
        "Question: Romeo and Juliet was written by William Shakespeare.\nAnswer: William Shakespeare",
    ],
    "v11_linear_equation": [
        "Question: If x + 5 = 12, what is x?\nAnswer: 7",
        "Question: Solve x + 5 = 12.\nAnswer: x = 7",
        "Question: If x + 8 = 20, what is x?\nAnswer: 12",
        "Question: Solve x + 9 = 17.\nAnswer: x = 8",
        "Question: If x - 4 = 10, what is x?\nAnswer: 14",
        "Question: Solve x - 6 = 13.\nAnswer: x = 19",
        "Question: If 2x = 18, what is x?\nAnswer: 9",
        "Question: Solve 3x = 21.\nAnswer: x = 7",
        "Question: If 2x + 3 = 11, what is x?\nAnswer: 4",
        "Question: Solve 3x - 7 = 14.\nAnswer: x = 7",
        "Question: x + 5 = 12 means x is 12 - 5.\nAnswer: 7",
        "Question: 3x - 7 = 14 means 3x = 21.\nAnswer: x = 7",
    ],
    "v11_percent_time_distance": [
        "Question: What is 25% of 200?\nAnswer: 50",
        "Question: If a train travels at 60 km/h for 2.5 hours, how far does it go?\nAnswer: 150 km",
        "Question: What is 15% of 80?\nAnswer: 12",
        "Question: What is 20% of 150?\nAnswer: 30",
        "Question: What is 40% of 250?\nAnswer: 100",
        "Question: What is 12.5% of 80?\nAnswer: 10",
        "Question: A car travels 50 km/h for 3 hours. How far does it go?\nAnswer: 150 km",
        "Question: A train travels 80 km/h for 2 hours. How far does it go?\nAnswer: 160 km",
        "Question: Distance equals speed times time. 60 times 2.5 equals what?\nAnswer: 150",
        "Question: What is 30% of 90?\nAnswer: 27",
        "Question: 25 percent of 200 equals 50.\nAnswer: 50",
        "Question: 60 km/h for 2.5 hours equals 150 km.\nAnswer: 150 km",
    ],
    "v11_circle_area": [
        "Question: Calculate the area of a circle with radius 3.\nAnswer: 9*pi, about 28.26",
        "Question: What is the area of a circle with radius 3?\nAnswer: 9*pi",
        "Question: Area of a circle is pi*r^2. If r = 3, what is the area?\nAnswer: 9*pi",
        "Question: What is pi times 3 squared?\nAnswer: 9*pi",
        "Question: Calculate the area of a circle with radius 2.\nAnswer: 4*pi",
        "Question: Calculate the area of a circle with radius 4.\nAnswer: 16*pi",
        "Question: Calculate the area of a circle with radius 5.\nAnswer: 25*pi",
        "Question: If radius is 6, circle area is what?\nAnswer: 36*pi",
        "Question: If r = 7, pi*r^2 is what?\nAnswer: 49*pi",
        "Question: A circle has radius 10. What is its area?\nAnswer: 100*pi",
        "Question: radius 3 gives area 28.26 approximately.\nAnswer: 28.26",
        "Question: pi times 9 is approximately 28.26.\nAnswer: 28.26",
    ],
    "v11_stats_number_theory": [
        "Question: What is the mean of 4, 8, 12, and 16?\nAnswer: 10",
        "Question: What is the GCD of 24 and 36?\nAnswer: 12",
        "Question: What is the LCM of 12 and 18?\nAnswer: 36",
        "Question: Mean of 4, 8, 12, 16 is (4+8+12+16)/4.\nAnswer: 10",
        "Question: What is the average of 5, 10, and 15?\nAnswer: 10",
        "Question: What is the mean of 2, 4, 6, and 8?\nAnswer: 5",
        "Question: What is the GCD of 18 and 24?\nAnswer: 6",
        "Question: What is the GCD of 30 and 45?\nAnswer: 15",
        "Question: What is the LCM of 4 and 6?\nAnswer: 12",
        "Question: What is the LCM of 8 and 12?\nAnswer: 24",
        "Question: GCD means greatest common divisor. GCD of 24 and 36 is 12.\nAnswer: 12",
        "Question: LCM means least common multiple. LCM of 12 and 18 is 36.\nAnswer: 36",
    ],
    "v11_factorial_derivative": [
        "Question: What is 7 factorial?\nAnswer: 5040",
        "Question: What is the derivative of x^3?\nAnswer: 3x^2",
        "Question: 7! equals 7*6*5*4*3*2*1.\nAnswer: 5040",
        "Question: What is 5 factorial?\nAnswer: 120",
        "Question: What is 6 factorial?\nAnswer: 720",
        "Question: What is 4 factorial?\nAnswer: 24",
        "Question: What is the derivative of x^2?\nAnswer: 2x",
        "Question: What is the derivative of x^4?\nAnswer: 4x^3",
        "Question: What is the derivative of 2x^3?\nAnswer: 6x^2",
        "Question: What is the derivative of 5x?\nAnswer: 5",
        "Question: Power rule: derivative of x^3 is 3x^2.\nAnswer: 3x^2",
        "Question: 7 factorial is 5040.\nAnswer: 5040",
    ],
}


def list_v07_categories() -> list[str]:
    """Return available v0.7 dataset names in a stable order."""
    return list(V07_DATASETS)


def get_v07_data(category: str) -> list[str]:
    """Return curated v0.7 training samples for a category."""
    if category not in V07_DATASETS:
        valid = ", ".join(list_v07_categories())
        raise KeyError(f"Unknown v0.7 dataset '{category}'. Valid datasets: {valid}")
    return V07_DATASETS[category]
