"""Select the best BitDPM v32 block/router setting from result JSON.

This is the bridge between the expensive core candidate scan and transfer
validation. It writes a small shell env file so the next commands can reuse the
chosen block path, sha, router, and scale without manual JSON inspection.
"""

from __future__ import annotations

import argparse
import json
import shlex
from pathlib import Path
from typing import Any


def load_runs(paths: list[str]) -> list[dict[str, Any]]:
    runs: list[dict[str, Any]] = []
    for raw in paths:
        path = Path(raw)
        if not path.exists():
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            data = [data]
        for row in data:
            if isinstance(row, dict) and "metadata" in row and "summary" in row:
                row = dict(row)
                row["_source"] = str(path)
                runs.append(row)
    return runs


def run_score(row: dict[str, Any]) -> tuple[int, float, int, int]:
    sm = row["summary"]
    return (
        int(sm.get("net", 0)),
        float(sm.get("routed", 0.0)),
        int(sm.get("fixes", 0)),
        -int(sm.get("active", 0)),
    )


def filter_candidates(
    runs: list[dict[str, Any]],
    benchmark: str,
    min_net: int,
    max_breaks: int,
    min_routed: float,
    prefer_router: str | None,
) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    for row in runs:
        md = row["metadata"]
        sm = row["summary"]
        if md.get("benchmark_set") != benchmark:
            continue
        if int(sm.get("net", 0)) < min_net:
            continue
        if int(sm.get("breaks", 0)) > max_breaks:
            continue
        if float(sm.get("routed", 0.0)) < min_routed:
            continue
        out.append(row)
    if prefer_router:
        preferred = [r for r in out if r["metadata"].get("router") == prefer_router]
        if preferred:
            return sorted(preferred, key=run_score, reverse=True)
    return sorted(out, key=run_score, reverse=True)


def shell_quote(value: Any) -> str:
    return shlex.quote("" if value is None else str(value))


def write_env(path: Path, row: dict[str, Any]) -> None:
    md = row["metadata"]
    sm = row["summary"]
    block = md.get("block", {})
    lines = [
        "# Generated by scripts/select_v32_best_block.py",
        f"export V31_BLOCK={shell_quote(md.get('block_path'))}",
        f"export V31_BLOCK_SHA256={shell_quote(md.get('block_sha256'))}",
        f"export V32_BEST_BLOCK_ID={shell_quote(block.get('block_id'))}",
        f"export V32_BEST_ROUTER={shell_quote(md.get('router'))}",
        f"export V32_BEST_SCALE={shell_quote(md.get('scale'))}",
        f"export V32_BEST_BENCHMARK={shell_quote(md.get('benchmark_set'))}",
        f"export V32_BEST_BASELINE={shell_quote(sm.get('baseline'))}",
        f"export V32_BEST_ROUTED={shell_quote(sm.get('routed'))}",
        f"export V32_BEST_FIXES={shell_quote(sm.get('fixes'))}",
        f"export V32_BEST_BREAKS={shell_quote(sm.get('breaks'))}",
        f"export V32_BEST_NET={shell_quote(sm.get('net'))}",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def make_markdown(row: dict[str, Any], source_files: list[str], env_path: str) -> str:
    md = row["metadata"]
    sm = row["summary"]
    block = md.get("block", {})
    fixes = sm.get("fixes_list", [])
    breaks = sm.get("breaks_list", [])
    lines = [
        "# BitDPM v32 Best Block Selection",
        "",
        "## Selected Run",
        "",
        f"- Source files: {', '.join(f'`{p}`' for p in source_files)}",
        f"- Benchmark: `{md.get('benchmark_set')}`",
        f"- Block: `{block.get('block_id')}`",
        f"- Block path: `{md.get('block_path')}`",
        f"- Block sha256: `{md.get('block_sha256')}`",
        f"- Router: `{md.get('router')}`",
        f"- Scale: `{md.get('scale')}`",
        f"- Score: {float(sm.get('baseline', 0)):.3f} -> {float(sm.get('routed', 0)):.3f}",
        f"- Fixes / breaks / net: {sm.get('fixes')} / {sm.get('breaks')} / {sm.get('net')}",
        f"- Active / disabled: {sm.get('active')} / {sm.get('disabled')}",
        "",
        "## Next Commands",
        "",
        "```bash",
        f"source {env_path}",
        "python scripts/run_v32_router_validation.py \\",
        '  --block-path "$V31_BLOCK" \\',
        "  --benchmark-set v08 \\",
        "  --routers unrestricted blacklist_only allow_math math_only \\",
        '  --scales "$V32_BEST_SCALE" \\',
        "  --device mps \\",
        "  --dtype float16 \\",
        "  --max-tokens 64 \\",
        "  --output-path experiments/reports/v32_v08_safety_router.json \\",
        "  --resume \\",
        "  --tag v32_v08_safety_router",
        "```",
        "",
    ]
    if fixes:
        lines.extend(["## Fixes", ""])
        lines.extend(f"- {item}" for item in fixes)
        lines.append("")
    if breaks:
        lines.extend(["## Breaks", ""])
        lines.extend(f"- {item}" for item in breaks)
        lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Select best v32 block from candidate scan JSON")
    parser.add_argument("json_files", nargs="+")
    parser.add_argument("--benchmark", default="core")
    parser.add_argument("--min-net", type=int, default=1)
    parser.add_argument("--max-breaks", type=int, default=0)
    parser.add_argument("--min-routed", type=float, default=0.0)
    parser.add_argument("--prefer-router", default=None)
    parser.add_argument("--env-out", default="experiments/reports/v32_best_block.env")
    parser.add_argument("--md-out", default="experiments/reports/v32_best_block.md")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    runs = load_runs(args.json_files)
    candidates = filter_candidates(
        runs,
        benchmark=args.benchmark,
        min_net=args.min_net,
        max_breaks=args.max_breaks,
        min_routed=args.min_routed,
        prefer_router=args.prefer_router,
    )
    if not candidates:
        raise SystemExit(
            "No matching candidate. Relax --min-net/--max-breaks/--min-routed or run expanded candidate scan."
        )
    selected = candidates[0]
    write_env(Path(args.env_out), selected)
    Path(args.md_out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.md_out).write_text(make_markdown(selected, args.json_files, args.env_out), encoding="utf-8")
    print(f"Selected: {selected['metadata'].get('block_path')}")
    print(f"Wrote env: {args.env_out}")
    print(f"Wrote report: {args.md_out}")


if __name__ == "__main__":
    main()
